FROM alpine:latest
ARG VAULT_VERSION="1.17.6"
ARG APP_ROOT=/usr/local/bin
ARG SRC=./docker/openshift

# Install dependencies
RUN apk add --no-cache \
    jq \
    aws-cli

WORKDIR ${APP_ROOT}

# Copy the shell script to the container
COPY ${SRC}/sync_secrets.sh ${APP_ROOT}/sync_secrets.sh

# Ensure that oc and SH script has executable permissions
RUN chmod +x ${APP_ROOT}/sync_secrets.sh

# Command to run the script
CMD [ "./sync_secrets.sh" ]