using System.Collections.Generic;
using MongoDB.EntityFrameworkCore;

namespace Scv.Db.Models;

/// <summary>
/// Auto-generated by the app to help relate objects to a given context (e.g. case)
/// </summary>
[Collection("labels")]
public class Label : EntityBase
{
    public const string CASE_FILE_ID = "Case File Id";
    public const string DIVISION = "Case Division";
    public const string CLASS = "Case Class";
    public const string JUDGE_ID = "Judge Id";

    public static readonly List<Label> ALL_LABELS =
    [
        new Label
        {
            Name = CASE_FILE_ID,
            Description = "Id that uniquely identify a case."
        },
        new Label
        {
            Name = JUDGE_ID,
            Description = "Id that uniquely identify the judge id in relation to Users collection."
        },
        new Label
        {
            Name = DIVISION,
            Description = "Identifies the type of case (e.g. Criminal, Small Claims, Family)"
        },
        new Label
        {
            Name = CLASS,
            Description = "Identifies the class of case (e.g. Youth, MVA, Enforcement, etc.)"
        }
    ];

    public string Name { get; set; }
    public string Description { get; set; }
}
