region              = "us-east-1"
app_name            = "jasper"
environment         = "snd"
test_s3_bucket_name = "test-s3-2-bucket"
kms_key_name        = "jasper-kms-key"
vpc_cidr            = "10.0.0.0/16"
subnet_1            = "10.0.1.0/24"
subnet_2            = "10.0.2.0/24"
