region              = "ca-central-1"
test_s3_bucket_name = "jasper-test-lz-s3-bucket-dev"
web_subnet_names    = ["Dev-Web-MainTgwAttach-B", "Dev-Web-MainTgwAttach-A"]
app_subnet_names    = ["Dev-App-A", "Dev-App-B"]
data_subnet_names   = ["Dev-Data-A", "Dev-Data-B"]
openshift_iam_user  = "openshiftuserdev"
iam_user_table_name = "BCGOV-LZA-IAM-USER-TABLE"
lb_name             = "default"
rds_db_ca_cert      = "rds-ca-rsa2048-g1"
cert_domain_name    = "internal.stratus.cloud.gov.bc.ca"
create_efs         = false
delete_protection_enabled = false
mongo_node_count    = 1
mongo_instance_type = "db.t3.medium"
mongousername       = "adminmongo"