name: Deploy to AWS
description: Deploy image to AWS Instance

inputs:
  environment:
    description: The environment to which the image will be deployed.
    required: true
  aws_account:
    description: The AWS Account ID.
    required: true
  region:
    description: The AWS Region of the AWS Account.
    required: true
  app_name:
    description: The application name.
    required: true
  aws_role_arn:
    description: The AWS Role ARN to assume.
    required: true

  # Image parameters
  ghcr_token:
    description: The token to use to login to the GHCR.
    required: true
  github_image_repo:
    description: The GCHR repo where images are stored.
    required: true
  image_name:
    description: The name of the image to be deployed.
    required: true
  image_digest:
    description: The digest of the image to be deployed. Identifies the unique image tag in the GHCR.
    required: true

env:
  AWS_ECR_REPO_URL: ${{ inputs.aws_account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.app_name }}-ecr-repo-${{ inputs.environment }}

runs:
  using: composite
  steps:
    - name: Log in to the GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_token }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-skip-session-tagging: true
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.aws_role_arn }}
        role-duration-seconds: 1800
        role-session-name: ci-deployment

    - name: Login to AWS CLI
      run: |
        aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin ${{ env.AWS_ECR_REPO_URL }}

    - name: Tag the image in the GHCR as ${{ inputs.environment }}
      shell: bash
      run: |
        docker pull ${{ github_image_repo}}${{ inputs.image_name }}@${{ inputs.image_digest }}
        docker tag ${{ github_image_repo}}${{ inputs.image_name }}@${{ inputs.image_digest }} ${{ env.AWS_ECR_REPO_URL }}:${{ inputs.image_name }}
        docker push ${{ env.AWS_ECR_REPO_URL }}:${{ inputs.image_name }}
