name: Build Web
description: Builds the Web codebase

inputs:
  working_directory:
    description: The working directory where the code will be built.
    required: true

runs:
  using: composite

  steps:
    - run: npm ci
      working-directory: ${{ inputs.working_directory }}

    # Lint errors exists from SCC and will be worked on separately.
    - run: npm run lint
      working-directory: ${{ inputs.working_directory }}
      continue-on-error: true

    - run: npm run build
      working-directory: ${{ inputs.working_directory }}

    # Unit test is not configured in SCC and will be worked on separately.
    - run: npm run test --if-present
      working-directory: ${{ inputs.working_directory }}
