version: "3.4"
services:

  web:
    image: scv-web
    environment:
      - API_URL=${API_URL}
      - USE_SELF_SIGNED_SSL=${USE_SELF_SIGNED_SSL}
      - IpFilterRules=${IpFilterRules}
      - RealIpFrom=${RealIpFrom}
      - WEB_BASE_HREF=${WEB_BASE_HREF}
      - IncludeSiteminderHeaders=${IncludeSiteminderHeaders}
    ports:
      - 8080:8080
    depends_on:
      - api

  web-dev:
    image: "scv-web-dev"
    environment:
      - API_URL=${API_URL}
      - WEB_BASE_HREF=${WEB_BASE_HREF}
      - DEV_MODE=false
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=notice
      - NPM_RUN=serve
    ports:
      - 8080:1339
    volumes:
      - "../web/src:/opt/app-root/src/src"
      - "../web/package.json:/opt/app-root/src/package.json"
    depends_on:
      - api

  api:
    image: scv-api
    environment: 
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - FileServicesClient__Username=${FileServicesClientUsername}
      - FileServicesClient__Password=${FileServicesClientPassword}
      - FileServicesClient__Url=${FileServicesClientUrl}
      - LookupServicesClient__Username=${LookupServicesClientUsername}
      - LookupServicesClient__Password=${LookupServicesClientPassword}
      - LookupServicesClient__Url=${LookupServicesClientUrl}
      - LocationServicesClient__Username=${LocationServicesClientUsername}
      - LocationServicesClient__Password=${LocationServicesClientPassword}
      - LocationServicesClient__Url=${LocationServicesClientUrl}
      - Request__ApplicationCd=${RequestApplicationCd}
      - Request__AgencyIdentifierId=${RequestAgencyIdentifierId}
      - Request__PartId=${RequestPartId}
      - Request__GetUserLoginDefaultAgencyId=${RequestGetUserLoginDefaultAgencyId}
      - Auth__UserId=${USER_ID}
      - Auth__UserPassword=${USER_PASSWORD}
      - Auth__AllowSiteMinderUserType=${ALLOW_SITE_MINDER_USER_TYPE}
      - DatabaseConnectionString=${DatabaseConnectionString}
      - DataProtectionKeyEncryptionKey=${DataProtectionKeyEncryptionKey}
      - Keycloak__Client=${KeycloakClient}
      - Keycloak__Authority=${KeycloakAuthority}
      - Keycloak__Secret=${KeycloakSecret}
      - Keycloak__Audience=${KeycloakAudience}
      - SiteMinderLogoutUrl=${SiteMinderLogoutUrl}
      - UserServicesClient__Username=${UserServicesClientUsername}
      - UserServicesClient__Password=${UserServicesClientPassword}
      - UserServicesClient__Url=${UserServicesClientUrl}
      - Keycloak__PresReqConfId=${KeycloakPresReqConfId}
      - Keycloak__VcIdpHint=${KeycloakVcIdpHint}
      - SplunkCollectorUrl=${SplunkCollectorUrl}
      - SplunkCollectorId=${SplunkCollectorId}
      - SplunkToken=${SplunkToken}
    ports:
      - 5000:5000
    volumes:
      - ../api/:/opt/app-root/src/api
      - ../db/:/opt/app-root/src/db
      - ../jc-interface-client/:/opt/app-root/src/jc-interface-client
      - scv-api-dev-bin:/opt/app-root/src/api/bin
      - scv-api-dev-obj:/opt/app-root/src/api/obj
      - ./seed:/opt/app-root/data
    depends_on:
      - db
    command: >
      /bin/bash -c "
        echo Waiting for the database service to start up ...;
        sleep 10;
        dotnet watch run --project /opt/app-root/src/api/api.csproj --urls='http://+:5000';"

  db:
    image: centos/postgresql-12-centos8
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./tmp:/tmp2

volumes:
  scv-api-dev-bin:
  scv-api-dev-obj: