version: '3.4'
services:
  web:
    image: '${COMPOSE_PROJECT_NAME}-web'
    environment:
      - API_URL=${API_URL}
      - USE_SELF_SIGNED_SSL=${USE_SELF_SIGNED_SSL}
      - IpFilterRules=${IpFilterRules}
      - RealIpFrom=${RealIpFrom}
      - WEB_BASE_HREF=${WEB_BASE_HREF}
      - IncludeSiteminderHeaders=${IncludeSiteminderHeaders}
    ports:
      - 8080:8080
    depends_on:
      - api

  web-dev:
    image: '${COMPOSE_PROJECT_NAME}-web-dev'
    environment:
      - API_URL=${API_URL}
      - WEB_BASE_HREF=${WEB_BASE_HREF}
      - DEV_MODE=false
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=notice
      - VITE_PORT=1339
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:1339'
    volumes:
      - '${LOCAL_WORKSPACE_FOLDER-..}/web/src:/opt/app-root/src/src'
      - '${LOCAL_WORKSPACE_FOLDER-..}/web/package.json:/opt/app-root/src/package.json'
    depends_on:
      - api

  api:
    image: '${COMPOSE_PROJECT_NAME}-api'
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - DEFAULT_USERS=${DEFAULT_USERS}
      - FileServicesClient__Username=${FileServicesClientUsername}
      - FileServicesClient__Password=${FileServicesClientPassword}
      - FileServicesClient__Url=${FileServicesClientUrl}
      - LookupServicesClient__Username=${LookupServicesClientUsername}
      - LookupServicesClient__Password=${LookupServicesClientPassword}
      - LookupServicesClient__Url=${LookupServicesClientUrl}
      - LocationServicesClient__Username=${LocationServicesClientUsername}
      - LocationServicesClient__Password=${LocationServicesClientPassword}
      - LocationServicesClient__Url=${LocationServicesClientUrl}
      - Request__ApplicationCd=${RequestApplicationCd}
      - Request__AgencyIdentifierId=${RequestAgencyIdentifierId}
      - Request__PartId=${RequestPartId}
      - Request__GetUserLoginDefaultAgencyId=${RequestGetUserLoginDefaultAgencyId}
      - Auth__UserId=${USER_ID}
      - Auth__UserPassword=${USER_PASSWORD}
      - Auth__AllowSiteMinderUserType=${ALLOW_SITE_MINDER_USER_TYPE}
      - DatabaseConnectionString=${DatabaseConnectionString}
      - DataProtectionKeyEncryptionKey=${DataProtectionKeyEncryptionKey}
      - Keycloak__Client=${KeycloakClient}
      - Keycloak__Authority=${KeycloakAuthority}
      - Keycloak__Secret=${KeycloakSecret}
      - Keycloak__Audience=${KeycloakAudience}
      - SiteMinderLogoutUrl=${SiteMinderLogoutUrl}
      - UserServicesClient__Username=${UserServicesClientUsername}
      - UserServicesClient__Password=${UserServicesClientPassword}
      - UserServicesClient__Url=${UserServicesClientUrl}
      - Keycloak__PresReqConfId=${KeycloakPresReqConfId}
      - Keycloak__VcIdpHint=${KeycloakVcIdpHint}
      - SplunkCollectorUrl=${SplunkCollectorUrl}
      - SplunkCollectorId=${SplunkCollectorId}
      - SplunkToken=${SplunkToken}
      - PCSS__Url=${PCSS_URL}
      - PCSS__Username=${PCSS_USERNAME}
      - PCSS__Password=${PCSS_PASSWORD}
      - PCSS__JudgeId=${PCSS_JUDGE_ID}
      - PCSS__JudgeHomeLocationId=${PCSS_JUDGE_HOME_LOCATION_ID}
      - AWS_API_GATEWAY_URL=${AWS_API_GATEWAY_URL}
      - AWS_API_GATEWAY_API_KEY=${AWS_API_GATEWAY_API_KEY}
      - AuthorizerKey=${AuthorizerKey}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_SERVER=${MONGODB_SERVER}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_PORT=${MONGODB_PORT}
    ports:
      - 5000:5000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER-..}/api/:/opt/app-root/src/api
      - ${LOCAL_WORKSPACE_FOLDER-..}/db/:/opt/app-root/src/db
      - ${LOCAL_WORKSPACE_FOLDER-..}/jc-interface-client/:/opt/app-root/src/jc-interface-client
      - ${LOCAL_WORKSPACE_FOLDER-..}/pcss-client/:/opt/app-root/src/pcss-client
      - api-dev-bin:/opt/app-root/src/api/bin
      - api-dev-obj:/opt/app-root/src/api/obj
      - ${LOCAL_WORKSPACE_FOLDER-.}/seed:/opt/app-root/data
    depends_on:
      - db-pg
      - db-mongo

    command: >
      /bin/bash -c "
        echo Waiting for the database service to start up ...;
        sleep 10;
        dotnet watch run --project /opt/app-root/src/api/api.csproj --urls='http://+:5000';"

  db-pg:
    image: centos/postgresql-12-centos8
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER-.}/tmp:/tmp2

  db-mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER-.}/tmp-mongo:/tmp-mongo

volumes:
  api-dev-bin:
  api-dev-obj:
