name: Build API
description: Builds the API codebase

inputs:
  working_directory:
    description: The working directory where the code will be built.
    required: true

runs:
  using: composite

  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.101

    - run: dotnet format --verify-no-changes --severity info
      shell: bash
      working-directory: ${{env.WORKING_DIRECTORY}}

    - run: dotnet restore
      shell: bash
      working-directory: ${{env.WORKING_DIRECTORY}}

    - run: dotnet build --configuration Release --no-restore
      shell: bash
      working-directory: ${{env.WORKING_DIRECTORY}}

    - run: dotnet test --no-restore --verbosity normal
      shell: bash
      working-directory: ${{env.WORKING_DIRECTORY}}
