name: App (Vue)

on:
  # PR targeting master is created or new commits are pushed
  push:
    branches:
      - master
    paths:
      - "web/**"

  # Manual trigger via GH Actions UI
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ./web
  IMAGE_NAME: web
  GITHUB_IMAGE_REPO: ghcr.io/bcgov/jasper/

jobs:
  build:
    name: Build, Create and Push Image
    runs-on: ubuntu-latest
    outputs:
      image_digest: ${{ steps.docker_push.outputs.digest }}

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Building Web codebase
        uses: ./.github/workflows/actions/build-web
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}
          node_version: ${{ matrix.node-version }}

      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"

      - name: Build Docker Image
        working-directory: ${{env.WORKING_DIRECTORY}}/../
        run: |
          docker build --tag web-runtime -f docker/nginx-runtime/Dockerfile ./docker/nginx-runtime/
          cd web
          docker build --tag web-artifacts -f Dockerfile.node . --build-arg WEB_BASE_HREF=/
          cd ..
          docker build --tag ${{ env.IMAGE_NAME }} -f docker/vue-on-nginx/Dockerfile ./docker/vue-on-nginx/
          docker tag ${{ env.IMAGE_NAME }} ${{ env.GITHUB_IMAGE_REPO }}${{ env.IMAGE_NAME }}:${{ steps.short_sha.outputs.SHORT_SHA }}

      - name: Push Image to GCHR
        id: docker_push
        run: |
          output=$(docker push ${{ env.GITHUB_IMAGE_REPO }}${{ env.IMAGE_NAME }}:${{ steps.short_sha.outputs.SHORT_SHA }})
          echo $output
          digest=$(echo "$output" | grep "digest: sha256" | awk '{ print $3 }')
          echo "digest=$digest" >> $GITHUB_OUTPUT

  deploy2dev:
    name: Deploy to DEV
    needs: build
    env:
      ENVIRONMENT: dev
    permissions:
      packages: write
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "${{ vars.AWS_ACCOUNT }}"

      - name: Deploy to ${{ env.ENVIRONMENT }}
        uses: ./.github/workflows/actions/deploy-to-aws
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws_account: ${{ vars.AWS_ACCOUNT }}
          region: ${{ vars.AWS_REGION }}
          app_name: ${{ vars.APP_NAME }}
          aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}
          github_image_repo: ${{ env.GITHUB_IMAGE_REPO }}
          image_name: ${{ env.IMAGE_NAME  }}
          image_digest: ${{ needs.build.outputs.image_digest }}

  # deploy2test:
  #   name: Deploy to TEST
  #   needs: [build, deploy2dev]
  #   env:
  #     ENVIRONMENT: test
  #   permissions:
  #     packages: write
  #   runs-on: ubuntu-latest
  #   environment: test

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Deploy to ${{ env.ENVIRONMENT }}
  #       uses: ./.github/worflows/actions/deploy-to-aws
  #       with:
  #         environment: ${{ env.ENVIRONMENT }}
  #         ghcr_token: ${{ secrets.GITHUB_TOKEN }}
  #         github_image_repo: ${{ env.GITHUB_IMAGE_REPO }}
  #         image_name: ${{ env.IMAGE_NAME  }}
  #         image_digest: ${{ needs.build.outputs.image_digest }}
