name: Web CI

on:
  # PR targeting master is created or new commits are pushed
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
    paths:
      - "web/**"

  # Manual trigger via GH Actions UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./web

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
        working-directory: ${{env.working-directory}}

      # Lint errors exists from SCC and will be worked on separately.
      - run: npm run lint
        working-directory: ${{env.working-directory}}
        continue-on-error: true

      - run: npm run build
        working-directory: ${{env.working-directory}}

      # Unit test is not configured in SCC and will be worked on separately.
      - run: npm run test --if-present
        working-directory: ${{env.working-directory}}
