name: Build Infra

on:
  # When a PR is created targeting master branch
  pull_request:
    branches:
      - master
    paths:
      - "infrastructure/**"

  # Manual trigger via GH Actions UI
  workflow_dispatch:
    inputs:
      environment:
        description: "Select target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  build-initial:
    uses: ./.github/workflows/aws-template-terraform.yml
    with:
      CONTEXT_FOLDER: "./infrastructure/cloud/environments/initial"
      CHANGE_FOLDER_NAME: environments/${{ inputs.environment || 'dev' }}
      ENVIRONMENT_NAME: ${{ inputs.environment || 'dev' }}
      APPLY_TF_CODE: false
    secrets: inherit

  build:
    needs: [build-initial]
    uses: ./.github/workflows/aws-template-terraform.yml
    with:
      CONTEXT_FOLDER: "./infrastructure/cloud/environments/${{ inputs.environment || 'dev' }}"
      CHANGE_FOLDER_NAME: environments/${{ inputs.environment || 'dev' }}
      ENVIRONMENT_NAME: ${{ inputs.environment || 'dev' }}
      APPLY_TF_CODE: false
    secrets: inherit
    