name: Publish Sync Secrets

on:
  workflow_dispatch:
  push:
    paths:
      - "docker/openshift/**"

env:
  IMAGE_NAME: sync-secrets
  GITHUB_IMAGE_REPO: ghcr.io/bcgov/jasper

permissions:
  id-token: write
  packages: write

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync Secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITHUB_IMAGE_REPO }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./docker/openshift/Dockerfile
          build-args: |
            SRC=../../docker/openshift