name: Publish Sync Secrets

on:
  workflow_dispatch:
  push:
    paths:
      - "docker/openshift/**"
      - "openshift/**"

env:
  IMAGE_NAME: sync-secrets
  GITHUB_IMAGE_REPO: ghcr.io/bcgov/jasper
  SRC_PATH: ../../openshift

permissions:
  id-token: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Images
    strategy:
      matrix:
        dockerfile-path:
          - ./docker/openshift/Dockerfile.sync-secrets
          - ./docker/openshift/Dockerfile.update-aws-creds
        image-name:
          - sync-secrets
          - update-aws-creds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITHUB_IMAGE_REPO }}/${{ matrix.image-name }}
          tags: |
            type=raw,value=latest

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ matrix.dockerfile-path }}
          build-args: |
            SRC=${{ env.SRC_PATH }}