name: Sync Secrets

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync Secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Openshift Cluster Login
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{ vars.OPENSHIFT_SERVER_URL }} 
          openshift_token: ${{ secrets.EMERALD_DEV_SA_PIPELINE_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ vars.OPENSHIFT_NAMESPACE }}-${{ vars.ENVIRONMENT }}

    steps:
      - name: Set conditional variable
        id: set_variable
        run: |
          if [[ "${{ vars.ENVIRONMENT }}" != "prod" ]]; then
            echo "MOUNT=${{ vars.OPENSHIFT_NAMESPACE }}-nonprod" >> $GITHUB_ENV
          else
            echo "MOUNT=${{ vars.OPENSHIFT_NAMESPACE }}-prod" >> $GITHUB_ENV
        shell: bash

      - name: Import secrets
        id: vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ vars.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          exportEnv: "false"
          namespace: platform-services
          secrets: |
            ${{ $MOUNT }}/data/helloworld hello=hello_value

      - name: Apply Secrets to AWS Secrets Manager
        # this does not do an "install" so assumes the helm chart already exists therefor won't work on init of a helm chart
        run: |
          echo "${{ steps.vault.outputs.hello_value }}"